services:
  db:
    image: postgres:17
    container_name: urlsystem-db-dev
    environment:
      POSTGRES_DB: url_system
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5309:5432"
    volumes:
      - db_dev_data:/data/postgres
    networks:
      - backend


  prometheus:
    container_name: sports_prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - db
    depends_on:
      - app
    restart: unless-stopped


  grafana:
    container_name: sports_grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - db
    depends_on:
      - prometheus
    restart: unless-stopped



volumes:
  db_dev_data:

networks:
  backend:
