services:
  db:
    image: postgres:17
    container_name: urlsystem-db-dev
    environment:
      POSTGRES_DB: url_system
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5309:5432"
    volumes:
      - db_dev_data:/data/postgres
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - backend
    restart: unless-stopped







volumes:
  db_dev_data:
  redis_data:

networks:
  backend:
