spring.application.name=url_system
spring.datasource.url=jdbc:postgresql://localhost:5309/url_system
spring.datasource.username=igor
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver



# JPA / Hibernate (common)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

# Flyway (common)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#JWT
spring.app.jwtSecret=VGhpc0lzQVNlY3JldEtleU5lZWRzQXQhTGVhc3QzMkJ5dGVzIQ==
spring.app.jwtExpirationMs=3000000

# Actuator (common)
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.enable.http=true


# Logging defaults (common)
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - [%X{requestId}] %msg%n


#KAFKA
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=email-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer



# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=200ms
spring.data.redis.connect-timeout=200ms


# How long to wait for a connection from the pool
spring.datasource.hikari.connection-timeout=1000
spring.jpa.properties.hibernate.jdbc.timeout=2



# =====================
# Resilience4j - CircuitBreaker
# =====================
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10

resilience4j.circuitbreaker.configs.default.recordExceptions[0]=org.springframework.dao.DataAccessException


resilience4j.circuitbreaker.instances.baseService.baseConfig=default
resilience4j.circuitbreaker.instances.baseService.slidingWindowSize=20
resilience4j.circuitbreaker.instances.baseService.waitDurationInOpenState=30s

resilience4j.circuitbreaker.instances.paymentService.baseConfig=default
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=40
resilience4j.circuitbreaker.instances.paymentService.slowCallRateThreshold=60
resilience4j.circuitbreaker.instances.paymentService.slowCallDurationThreshold=2s


# =====================
# Resilience4j - Retry
# =====================
resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=1000
resilience4j.retry.configs.default.enableExponentialBackoff=true
resilience4j.retry.configs.default.exponentialBackoffMultiplier=2

# Retry only transient infra problems
resilience4j.retry.instances.baseService.retryExceptions[0]=org.springframework.dao.DataAccessException
resilience4j.retry.instances.baseService.retryExceptions[1]=org.springframework.dao.QueryTimeoutException
resilience4j.retry.instances.baseService.retryExceptions[2]=org.springframework.dao.DataAccessResourceFailureException

# Never retry business/domain exceptions
resilience4j.retry.instances.baseService.ignoreExceptions[0]=java.util.NoSuchElementException
resilience4j.retry.instances.baseService.ignoreExceptions[1]=com.example.url_system.exceptions.UrlExpiredException



resilience4j.retry.instances.baseService.baseConfig=default
resilience4j.retry.instances.baseService.maxAttempts=4
resilience4j.retry.instances.baseService.waitDuration=500
resilience4j.retry.instances.baseService.enableExponentialBackoff=true
resilience4j.retry.instances.baseService.exponentialBackoffMultiplier=2

resilience4j.retry.instances.databaseService.maxAttempts=2
resilience4j.retry.instances.databaseService.waitDuration=100
resilience4j.retry.instances.databaseService.enableExponentialBackoff=true
resilience4j.retry.instances.databaseService.exponentialBackoffMultiplier=2



# =====================
# Resilience4j - Bulkhead
# =====================
resilience4j.bulkhead.configs.default.maxConcurrentCalls=25
resilience4j.bulkhead.configs.default.maxWaitDuration=100ms

resilience4j.bulkhead.instances.baseService.baseConfig=default
resilience4j.bulkhead.instances.baseService.maxConcurrentCalls=10

resilience4j.bulkhead.instances.databaseService.maxConcurrentCalls=50


# =====================
# Resilience4j - ThreadPoolBulkhead
# =====================
resilience4j.thread-pool-bulkhead.configs.default.maxThreadPoolSize=4
resilience4j.thread-pool-bulkhead.configs.default.coreThreadPoolSize=2
resilience4j.thread-pool-bulkhead.configs.default.queueCapacity=100
resilience4j.thread-pool-bulkhead.configs.default.keepAliveDuration=20ms

resilience4j.thread-pool-bulkhead.instances.heavyOperation.baseConfig=default
resilience4j.thread-pool-bulkhead.instances.heavyOperation.maxThreadPoolSize=8
resilience4j.thread-pool-bulkhead.instances.heavyOperation.coreThreadPoolSize=4


# =====================
# Resilience4j - TimeLimiter
# =====================
resilience4j.timelimiter.configs.default.cancelRunningFuture=true
resilience4j.timelimiter.configs.default.timeoutDuration=2s

resilience4j.timelimiter.instances.baseService.baseConfig=default
resilience4j.timelimiter.instances.baseService.timeoutDuration=3s

resilience4j.timelimiter.instances.quickOperation.timeoutDuration=1s