spring.application.name=url_system
server.port=${SERVER_PORT:8080}

# =====================
# DB (RDS)
# =====================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari (prod)
spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX:20}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN_IDLE:5}
spring.datasource.hikari.connection-timeout=${DB_CONN_TIMEOUT_MS:3000}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# =====================
# Security / JWT
# =====================
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS:3000000}

# =====================
# Redis (ElastiCache)
# =====================
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:true}
spring.data.redis.timeout=${REDIS_TIMEOUT_MS:5000ms}
spring.data.redis.connect-timeout=${REDIS_CONNECT_TIMEOUT_MS:5000ms}


# =====================
# Observability / Actuator (ALB/ECS-friendly)
# =====================

management.endpoints.web.exposure.include=health,info,metrics,prometheus,circuitbreakers,ratelimiters,retries,bulkheads
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always

management.metrics.tags.application=${spring.application.name}
management.metrics.tags.env=prod



# =====================
# Logging
# =====================
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - [%X{requestId}] %msg%n

# =====================
# Email (temporary SMTP) - ok for first deploy
# =====================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SSL_TRUST:smtp.gmail.com}
spring.mail.properties.mail.smtp.ssl.checkserveridentity=true
app.publicBaseUrl=${PUBLIC_BASE_URL:url-alb-13546580.eu-north-1.elb.amazonaws.com}


# ===============
# S3 Avatars
# ===============
app.s3.avatars.bucket=url-system-avatars
app.s3.avatars.region=eu-north-1
app.s3.avatars.keyPrefix=avatars
app.s3.avatars.presignTtlSeconds=600


# ================
# SQS
# ================
app.sqs.emailQueue=${EMAIL_QUEUE_NAME:url-email-queue}
spring.cloud.aws.region.static=eu-north-1
app.sqs.enabled=${APP_SQS_ENABLED:true}


# ================
# STRIPE
# ================
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.premium-price-id=${STRIPE_PREMIUM_PRICE_ID}
stripe.success-url=${STRIPE_SUCCESS_URL}
stripe.cancel-url=${STRIPE_CANCEL_URL}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
