spring.application.name=url_system
spring.datasource.url=jdbc:postgresql://localhost:5309/url_system
spring.datasource.username=igor
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver



# JPA / Hibernate (common)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

# Flyway (common)
spring.flyway.enabled=true
spring.flyway.locations=classpath:migration

#JWT
spring.app.jwtSecret=VGhpc0lzQVNlY3JldEtleU5lZWRzQXQhTGVhc3QzMkJ5dGVzIQ==
spring.app.jwtExpirationMs=3000000

#Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.metrics.enable.http=true
