name: Tests

on:
  pull_request:
  push:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESTCONTAINERS_RYUK_DISABLED: "true"
      TESTCONTAINERS_REUSE_ENABLE: "false"
    steps:
      - uses: actions/checkout@v4

      - name: Debug Docker
        run: |
          docker --version
          docker info
          docker ps

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - run: chmod +x mvnw
      - run: ./mvnw clean verify

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
